spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?useSSL=false
    username: root
    password: goodlunch
  
logging: 
  level:
    root: INFO
    jp.co.sparkworks.restaurant: TRACE