spring:
  datasource:
    url: jdbc:mysql://pandamall.cdc84a0kqzmn.ap-northeast-1.rds.amazonaws.com:3306/arapp?useSSL=false
    username: goodlunch
    password: goodlunch
  
logging: 
  level:
    root: INFO
    jp.co.sparkworks.restaurant: TRACE