spring:
  datasource:
    url: jdbc:mysql://sparkworks.c0taibnfhlog.ap-northeast-1.rds.amazonaws.com:3306/restaurant?useSSL=false
    username: sparkworks
    password: sparkworks

logging:
  level:
    root: INFO
    jp.co.sparkworks.restaurant: TRACE